services:
  db:
    image: postgres:17.5
    container_name: city17_db
    env_file:
      - postgres.env
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

    # Uncomment to enable logging of all queries
    # command: ["postgres", "-c", "log_statement=all"]

volumes:
  db_data: {}
